[package]
name = "launcher"
version = "1.1.3"
license = "GPL-3,0-or-later"
description = "A Wayland-native system launcher"
readme = "README.md"
homepage = "https://github.com/mnussbaum/launcher"
repository = "https://github.com/mnussbaum/launcher"
authors = ["mnussbaum <michaelnussbaum08@gmail.com>"]
edition = "2018"

[dependencies.gtk]
version = "0.6"
features = ["v3_16"]

[dependencies.glib]
version = "0.8.1"

[dependencies.gio]
version = "0.6"
